#Enviroment URLs
baseURLweb=http://localhost:4200/login
baseURLapi=http://localhost:56740
token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJlM2NmNTY5ZC0zMzMyLTQ3NGYtYTdiNS1iNzYyM2U3M2ZjN2UiLCJyb2xlIjoiQWRtaW4iLCJVc2VyTmFtZSI6ImFkbWluIiwibmJmIjoxNzgyNzI4NDUyLCJleHAiOjE3ODI4MTQ4NTIsImlhdCI6MTc4MjcyODQ1Mn0.KqixP2gBLLoZntSGOKqGPmeboPw4o3tM8DOIrDb3jk4
pointOfSaleDocumentId=6a3250d9d4b72754bc18ab73
