#Enviroment URLs
baseURLweb=http://localhost:4200/login
baseURLapi=http://localhost:56740
token=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJkNWVmNmQxMS0wZGRlLTQxODEtYjE4ZC02OTk0ZDdiZjljZjUiLCJyb2xlIjoiQWRtaW4iLCJVc2VyTmFtZSI6ImFkbWluIiwibmJmIjoxNzc3NDUzNDYwLCJleHAiOjE3Nzc1Mzk4NjAsImlhdCI6MTc3NzQ1MzQ2MH0.7OYzzezii_7KHwWed41eTSWhsZf2SeIr4ho-IgZuWjI
pointOfSaleDocumentId=69537e033bba8b33ecb0b555
