#Enviroment URLs
baseURLweb=http://localhost:4200/login
baseURLapi=http://localhost:56740
token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VySUQiOiJkMWYyYzY3Ny1kOGQ3LTQxMGUtODgzMC0yMzc3NmY2OGNjNzkiLCJyb2xlIjoiQWRtaW4iLCJVc2VyTmFtZSI6ImFkbWluIiwibmJmIjoxNzc1NjQ4OTM5LCJleHAiOjE3NzU3MzUzMzksImlhdCI6MTc3NTY0ODkzOX0.dUe6_twKGhH2HB5kfDQ8wWIxlUkYthzv3Ha8kYU2HYA
pointOfSaleDocumentId=6903c153f6a6de2248add31d
